# Generated by Django 4.2.13 on 2024-07-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_create_customers',
            field=models.BooleanField(default=False),
        ),
    ]
