# Generated by Django 4.2.13 on 2024-07-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_can_create_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_manage_users',
            field=models.BooleanField(default=False),
        ),
    ]
