# Generated by Django 4.2.13 on 2024-07-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryitem_options_alter_inventoryitem_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='delete_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
