# Generated by Django 4.2.13 on 2024-07-28 02:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20240709_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tab_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='customertab',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tab', to='customers.customer'),
        ),
    ]
